import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Passenger Portal
    book: 'Book',
    myTrips: 'My Trips',
    selectServices: 'Select services',
    journeyDetails: 'Journey details',
    confirmBooking: 'Confirm booking',
    heroA: 'Travel with',
    heroB: 'confidence.',
    heroSub: 'Pick services, book in seconds, track your assistant live.',
    verified: 'Verified assistants',
    station: 'Station',
    date: 'Date',
    time: 'Time',
    active: 'Active',
    history: 'History',
    viewLive: 'View live',
    cancel: 'Cancel',
    noActive: 'No active bookings.',
    bookFirst: 'Book your first trip',
    noHistory: 'No past trips yet.',
    settings: 'Settings',
    language: 'Language',
    appearance: 'Appearance',
    light: 'Light',
    dark: 'Dark',
    logout: 'Logout',
    safety: 'Safety',
    help: 'Help & Support',
    myJobs: 'My Assigned Jobs',
    earnings: 'Earnings & Reviews',
    account: 'Account',
    role: 'Role',

    // Assistant Portal — Header & Duty
    assistantDuty: 'ASSISTANT DUTY',
    makingJourneyEasier: 'Making Every Journey Easier.',
    onDuty: 'On Duty',
    offDuty: 'Off Duty',
    stationDutyStatus: 'Station Duty Status',
    goOnDuty: 'Go On Duty',
    goOffDuty: 'Go Off Duty',
    activatingDuty: 'Activating duty...',
    deactivatingDuty: 'Deactivating duty...',
    liveDispatchDutyDesc: "You're currently receiving real-time assistance dispatches at",
    offDutyDesc: 'Go On Duty to start receiving passenger luggage & escort requests.',
    dutyActiveMsg: "You're now on duty at",
    waitingForRequests: 'Waiting for passenger requests.',
    dutyInactiveMsg: 'You are now off duty.',
    switchStation: 'Select Station',

    // Assistant Portal — Navigation Tabs
    dashboard: 'Dashboard',
    availableRequests: 'Available Requests',
    myAssignedJob: 'My Assigned Job',
    tripHistory: 'Trip History',
    earningsReviews: 'Earnings & Reviews',
    profile: 'Profile',
    support: 'Support',

    // Greetings & Section Headers
    goodMorning: 'GOOD MORNING',
    goodAfternoon: 'GOOD AFTERNOON',
    goodEvening: 'GOOD EVENING',
    readyNextPassenger: "You're ready for your next passenger.",
    stationPresentTime: 'STATION PRESENT TIME',
    yourCurrentStation: 'YOUR CURRENT STATION',
    currentDutyStatus: 'CURRENT DUTY STATUS',
    stationDispatchActive: 'Station Dispatch Active',
    offDutyStandby: 'Off Duty / Standby',
    switchDuty: 'Switch Duty',
    dispatchBoard: 'DISPATCH BOARD',
    activeAssignment: 'ACTIVE ASSIGNMENT',
    completedTripsRecord: 'COMPLETED TRIPS RECORD',
    payoutsFeedback: 'PAYOUTS & FEEDBACK',
    dutyIdentity: 'DUTY IDENTITY & BADGE',
    helpDesk: 'HELP DESK & SAFETY',

    // Metrics Cards
    stationRequests: 'STATION REQUESTS',
    waitingForPickup: 'Waiting for pickup',
    activeJobsCount: 'ACTIVE JOBS',
    inProgress: 'In progress',
    completedJobsCount: 'COMPLETED JOBS',
    assistedPassengers: 'Assisted passengers',
    totalEarnings: 'TOTAL EARNINGS',
    directPayouts: 'Direct payouts',
    averageRating: 'AVERAGE RATING',
    verifiedReviews: 'Verified reviews',

    // Available Requests Section
    realTimeRequestsAt: 'Real-time passenger assistance requests at',
    noRequestsAtStation: 'No pending passenger requests at this station.',
    requestsAppearHere: "You're all caught up. When a passenger requests assistance, it will appear here in real time.",
    acceptRequest: 'Accept Request',
    accepting: 'Accepting...',
    pnr: 'PNR',
    platform: 'Platform',
    coach: 'Coach',
    luggageBags: 'Luggage / Bags',
    fare: 'Fare',
    train: 'Train',
    passenger: 'Passenger',

    // Job Card & Actions
    manageJobSub: 'Manage and complete your current passenger assistance job.',
    noActiveJob: 'No active job right now.',
    acceptToStart: 'Accept a request from the Available Requests board to start your duty assignment.',
    viewRequestsBtn: 'View Available Requests',
    atPlatform: "I'm at Platform",
    verifyStartService: 'Verify & Start Service',
    completeService: 'Complete Service',
    enterOtpPrompt: 'Enter 6-digit passenger OTP',
    verifyOtp: 'Verify OTP',
    verifying: 'Verifying...',
    otpVerified: 'OTP Verified',
    callPassenger: 'Call',
    chatPassenger: 'Chat',
    platformConfirmed: 'Confirmed',
    platformChanged: 'Platform Changed',
    emergencySos: 'Station Emergency SOS',
    wheelchair: 'Wheelchair Assistance',
    porterService: 'Coolie / Porter Service',
    otpInstruction: 'Ask the passenger for their 6-digit secret OTP upon reaching the coach.',

    // Trip History Section
    tripHistorySub: 'Record of all completed and past assistance assignments',
    bookingId: 'Booking ID',
    status: 'Status',
    completed: 'Completed',
    cancelled: 'Cancelled',
    rating: 'Rating',
    noCompletedJobs: 'No completed jobs yet.',
    completedWillAppear: 'Your completed assignments and passenger ratings will appear here.',
    servicesSelected: 'Services Selected',

    // Earnings & Reviews Section
    earningsSub: 'Track your income, completed trips, and passenger ratings',
    totalPayouts: 'Total Payouts',
    ratedTrips: 'Rated Trips',
    passengerReviews: 'Passenger Reviews',
    noReviewsYet: 'No passenger reviews yet.',
    recentFeedback: 'Recent Passenger Feedback',

    // Profile & Support Section
    profileSub: 'Manage your credentials, duty station, and operational safety',
    assistantProfile: 'Assistant Profile',
    kycStatus: 'KYC Status',
    verifiedBadge: 'Verified',
    badgeNumber: 'Badge Number',
    phoneNumber: 'Phone Number',
    assignedStation: 'Assigned Station',
    helpEmergencySupport: 'Help & Emergency Support',
    railwayHelpline139: 'Dial 139 - Railway Passenger Helpline',
    policeHelpline112: 'Dial 112 - National Emergency Support',
    safetyProtocols: 'Operational Safety Guidelines',
    supportSub: '24/7 Platform assistance & emergency contacts',
    callNow: 'Call Now',
    copyNumber: 'Copy Number',
    copied: 'Copied!',
    stationControlRoom: '139 Control Room',
    policeHelpline: '112 Emergency Hotline',
    stationHubInfo: 'Station Desk & Emergency Hub',
    reportIssueTitle: 'Report Operational Issue to Station Desk',
    reportIssueSub: 'Encountered a coach no-show, luggage dispute or platform change? Dispatch an urgent operational ticket to the Station Master.',
    category: 'Issue Category',
    passengerNoShow: 'Passenger Not Found / Coach No-Show',
    luggageDispute: 'Excess Luggage / Weight Dispute',
    platformChangeNotice: 'Sudden Platform Change',
    paymentDispute: 'Payment / Fare Discrepancy',
    medicalEmergency: 'Immediate Medical / Stretcher Support',
    otherQuery: 'Other Concourse Issue',
    pnrOptional: 'PNR / Booking ID (Optional)',
    describeIssue: 'Describe the situation at the platform...',
    submitTicket: 'Dispatch Ticket to Station Desk',
    ticketSubmitted: 'Ticket Dispatched to Station Supervisor',
    recentTickets: 'Recent Station Desk Tickets',
    noRecentTickets: 'No operational tickets raised today.',
    protocolsTitle: 'Platform Assistant Safety Protocols & FAQs',

    // Modals & Popovers
    confirmOffDuty: 'Confirm Off Duty',
    confirmOffDutyDesc: 'Are you sure you want to go off duty? You will no longer receive new passenger requests.',
    stayOnDuty: 'Stay On Duty',
    confirmGoOffDuty: 'Yes, Go Off Duty',
    activeJobWarning: 'Active Job in Progress',
    activeJobWarningDesc: 'You cannot go off duty while you have an active assigned job. Please complete your current passenger assignment first.',
    notificationsTitle: 'Notifications',
    notificationsSub: 'Station Dispatch & Operational Alerts',
    markAllRead: 'Mark all read',
    allCaughtUp: 'All caught up!',
    noPendingAlerts: 'No pending dispatch alerts. You will be notified instantly when a passenger requests assistance.',
    newDispatch: 'New Dispatch',
    activeJobAlert: 'Active Job',
    stationRadar: 'Station Radar',
  },

  te: {
    // Passenger Portal
    book: 'బుక్',
    myTrips: 'నా ప్రయాణాలు',
    selectServices: 'సేవలను ఎంచుకోండి',
    journeyDetails: 'ప్రయాణ వివరాలు',
    confirmBooking: 'బుకింగ్ కన్ఫర్మ్ చేయండి',
    heroA: 'ప్రయాణించండి',
    heroB: 'నమ్మకంతో.',
    heroSub: 'సేవలు ఎంచుకోండి, సెకన్లలో బుక్ చేయండి, అసిస్టెంట్‌ను లైవ్‌గా ట్రాక్ చేయండి.',
    verified: 'ధృవీకరించిన అసిస్టెంట్లు',
    station: 'స్టేషన్',
    date: 'తేదీ',
    time: 'సమయం',
    active: 'యాక్టివ్',
    history: 'చరిత్ర',
    viewLive: 'లైవ్ చూడండి',
    cancel: 'రద్దు చేయండి',
    noActive: 'యాక్టివ్ బుకింగ్‌లు లేవు.',
    bookFirst: 'మీ మొదటి ప్రయాణం బుక్ చేయండి',
    noHistory: 'ఇంకా ప్రయాణాలు లేవు.',
    settings: 'సెట్టింగ్‌లు',
    language: 'భాష',
    appearance: 'థీమ్',
    light: 'లైట్',
    dark: 'డార్క్',
    logout: 'లాగ్ అవుట్',
    safety: 'భద్రత',
    help: 'సహాయం & మద్దతు',
    myJobs: 'నాకు కేటాయించిన పనులు',
    earnings: 'ఆదాయం & సమీక్షలు',
    account: 'ఖాతా',
    role: 'పాత్ర',

    // Assistant Portal — Header & Duty
    assistantDuty: 'అసిస్టెంట్ డ్యూటీ',
    makingJourneyEasier: 'ప్రతి ప్రయాణాన్ని సులభతరం చేస్తూ.',
    onDuty: 'డ్యూటీలో ఉన్నారు',
    offDuty: 'డ్యూటీలో లేరు',
    stationDutyStatus: 'స్టేషన్ డ్యూటీ స్థితి',
    goOnDuty: 'డ్యూటీ ప్రారంభించు',
    goOffDuty: 'డ్యూటీ ముగించు',
    activatingDuty: 'డ్యూటీ యాక్టివేట్ అవుతోంది...',
    deactivatingDuty: 'డ్యూటీ ముగుస్తోంది...',
    liveDispatchDutyDesc: 'మీరు ప్రస్తుతం నిజ-సమయ సహాయ అభ్యర్థనలను అందుకుంటున్నారు:',
    offDutyDesc: 'ప్రయాణీకుల లగేజీ మరియు సహాయ అభ్యర్థనలను స్వీకరించడానికి డ్యూటీని ప్రారంభించండి.',
    dutyActiveMsg: 'మీరు ఇప్పుడు డ్యూటీలో ఉన్నారు:',
    waitingForRequests: 'ప్రయాణీకుల అభ్యర్థనల కోసం వేచి ఉంది.',
    dutyInactiveMsg: 'మీరు ఇప్పుడు ఆఫ్ డ్యూటీలో ఉన్నారు.',
    switchStation: 'స్టేషన్‌ను ఎంచుకోండి',

    // Assistant Portal — Navigation Tabs
    dashboard: 'డాష్‌బోర్డ్',
    availableRequests: 'అందుబాటులో ఉన్న అభ్యర్థనలు',
    myAssignedJob: 'నాకు కేటాయించిన పని',
    tripHistory: 'ప్రయాణాల చరిత్ర',
    earningsReviews: 'ఆదాయం & సమీక్షలు',
    profile: 'ప్రొఫైల్',
    support: 'సహాయం & మద్దతు',

    // Greetings & Section Headers
    goodMorning: 'శుభోదయం',
    goodAfternoon: 'శుభ మధ్యాహ్నం',
    goodEvening: 'శుభ సాయంత్రం',
    readyNextPassenger: 'మీరు తదుపరి ప్రయాణీకుడి కోసం సిద్ధంగా ఉన్నారు.',
    stationPresentTime: 'స్టేషన్ ప్రస్తుత సమయం',
    yourCurrentStation: 'మీ ప్రస్తుత స్టేషన్',
    currentDutyStatus: 'ప్రస్తుత డ్యూటీ స్థితి',
    stationDispatchActive: 'స్టేషన్ డిస్పాచ్ యాక్టివ్',
    offDutyStandby: 'డ్యూటీలో లేరు / స్టాండ్‌బై',
    switchDuty: 'డ్యూటీ మార్చండి',
    dispatchBoard: 'డిస్పాచ్ బోర్డు',
    activeAssignment: 'యాక్టివ్ అసైన్‌మెంట్',
    completedTripsRecord: 'పూర్తయిన ప్రయాణాల రికార్డు',
    payoutsFeedback: 'చెల్లింపులు & ఫీడ్‌బ్యాక్',
    dutyIdentity: 'డ్యూటీ గుర్తింపు & బ్యాడ్జ్',
    helpDesk: 'సహాయ కేంద్రం & భద్రత',

    // Metrics Cards
    stationRequests: 'స్టేషన్ అభ్యర్థనలు',
    waitingForPickup: 'పికప్ కోసం వేచి ఉంది',
    activeJobsCount: 'యాక్టివ్ జాబ్స్',
    inProgress: 'పురోగతిలో ఉంది',
    completedJobsCount: 'పూర్తయిన పనులు',
    assistedPassengers: 'సహాయం పొందిన ప్రయాణీకులు',
    totalEarnings: 'మొత్తం ఆదాయం',
    directPayouts: 'ప్రత్యక్ష చెల్లింపులు',
    averageRating: 'సగటు రేటింగ్',
    verifiedReviews: 'ధృవీకరించిన సమీక్షలు',

    // Available Requests Section
    realTimeRequestsAt: 'వద్ద నిజ-సమయ ప్రయాణీకుల సహాయ అభ్యర్థనలు:',
    noRequestsAtStation: 'ఈ స్టేషన్‌లో ప్రస్తుతం ఎటువంటి పెండింగ్ అభ్యర్థనలు లేవు.',
    requestsAppearHere: 'అంతా సిద్ధంగా ఉంది. ప్రయాణీకుడు సహాయం కోరినప్పుడు, అది ఇక్కడ నిజ సమయంలో కనిపిస్తుంది.',
    acceptRequest: 'అభ్యర్థనను అంగీకరించండి',
    accepting: 'అంగీకరిస్తోంది...',
    pnr: 'PNR',
    platform: 'ప్లాట్‌ఫారమ్',
    coach: 'కోచ్',
    luggageBags: 'లగేజీ / బ్యాగులు',
    fare: 'ఛార్జీ',
    train: 'రైలు',
    passenger: 'ప్రయాణీకుడు',

    // Job Card & Actions
    manageJobSub: 'మీ ప్రస్తుత ప్రయాణీకుల సహాయ పనిని నిర్వహించండి మరియు పూర్తి చేయండి.',
    noActiveJob: 'ప్రస్తుతం ఏ యాక్టివ్ జాబ్ లేదు.',
    acceptToStart: 'మీ డ్యూటీ ప్రారంభించడానికి అందుబాటులో ఉన్న అభ్యర్థనల బోర్డు నుండి ఒక అభ్యర్థనను అంగీకరించండి.',
    viewRequestsBtn: 'అందుబాటులో ఉన్న అభ్యర్థనలను చూడండి',
    atPlatform: 'నేను ప్లాట్‌ఫారమ్ వద్ద ఉన్నాను',
    verifyStartService: 'ధృవీకరించి సేవను ప్రారంభించండి',
    completeService: 'సేవను పూర్తి చేయండి',
    enterOtpPrompt: 'ప్రయాణీకుడి 6-అంకెల OTP ని నమోదు చేయండి',
    verifyOtp: 'OTP ని ధృవీకరించండి',
    verifying: 'ధృవీకరిస్తోంది...',
    otpVerified: 'OTP ధృవీకరించబడింది',
    callPassenger: 'కాల్ చేయండి',
    chatPassenger: 'చాట్ చేయండి',
    platformConfirmed: 'ధృవీకరించబడింది',
    platformChanged: 'ప్లాట్‌ఫారమ్ మారింది',
    emergencySos: 'స్టేషన్ అత్యవసర SOS',
    wheelchair: 'వీల్‌చైర్ సహాయం',
    porterService: 'కూలీ / పోర్టర్ సేవ',
    otpInstruction: 'కోచ్ వద్దకు చేరుకున్న తర్వాత ప్రయాణీకుడిని 6-అంకెల రహస్య OTP అడగండి.',

    // Trip History Section
    tripHistorySub: 'పూర్తయిన మరియు గత సహాయ పనుల రికార్డు',
    bookingId: 'బుకింగ్ ID',
    status: 'స్థితి',
    completed: 'పూర్తయింది',
    cancelled: 'రద్దు చేయబడింది',
    rating: 'రేటింగ్',
    noCompletedJobs: 'ఇంకా పూర్తయిన పనులు లేవు.',
    completedWillAppear: 'మీరు పూర్తి చేసిన పనులు మరియు ప్రయాణీకుల రేటింగ్‌లు ఇక్కడ కనిపిస్తాయి.',
    servicesSelected: 'ఎంచుకున్న సేవలు',

    // Earnings & Reviews Section
    earningsSub: 'మీ ఆదాయం, పూర్తయిన ప్రయాణాలు మరియు ప్రయాణీకుల రేటింగ్‌లను ట్రాక్ చేయండి',
    totalPayouts: 'మొత్తం చెల్లింపులు',
    ratedTrips: 'రేటింగ్ పొందిన ప్రయాణాలు',
    passengerReviews: 'ప్రయాణీకుల సమీక్షలు',
    noReviewsYet: 'ఇంకా ప్రయాణీకుల సమీక్షలు లేవు.',
    recentFeedback: 'ఇటీవలి ప్రయాణీకుల ఫీడ్‌బ్యాక్',

    // Profile & Support Section
    profileSub: 'మీ ఆధారాలు, డ్యూటీ స్టేషన్ మరియు కార్యాచరణ భద్రతను నిర్వహించండి',
    assistantProfile: 'అసిస్టెంట్ ప్రొఫైల్',
    kycStatus: 'KYC స్థితి',
    verifiedBadge: 'ధృవీకరించబడింది',
    badgeNumber: 'బ్యాడ్జ్ నంబర్',
    phoneNumber: 'ఫోన్ నంబర్',
    assignedStation: 'కేటాయించిన స్టేషన్',
    helpEmergencySupport: 'సహాయం & అత్యవసర మద్దతు',
    railwayHelpline139: 'డయల్ 139 - రైల్వే ప్రయాణీకుల హెల్ప్‌లైన్',
    policeHelpline112: 'డయల్ 112 - జాతీయ అత్యవసర మద్దతు',
    safetyProtocols: 'కార్యాచరణ భద్రతా మార్గదర్శకాలు',
    supportSub: '24/7 ప్లాట్‌ఫారమ్ సహాయం & అత్యవసర పరిచయాలు',
    callNow: 'ఇప్పుడే కాల్ చేయండి',
    copyNumber: 'నంబర్ కాపీ చేయండి',
    copied: 'కాపీ చేయబడింది!',
    stationControlRoom: '139 కంట్రోల్ రూమ్',
    policeHelpline: '112 అత్యవసర హాట్‌లైన్',
    stationHubInfo: 'స్టేషన్ డెస్క్ & అత్యవసర కేంద్రం',
    reportIssueTitle: 'స్టేషన్ డెస్క్‌కు కార్యాచరణ సమస్యను నివేదించండి',
    reportIssueSub: 'కోచ్ వద్ద ప్రయాణీకుడు లేకపోవడం, లగేజీ వివాదం లేదా ప్లాట్‌ఫారమ్ మార్పు ఎదురైందా? స్టేషన్ మాస్టర్‌కు అత్యవసర టిక్కెట్‌ను పంపండి.',
    category: 'సమస్య వర్గం',
    passengerNoShow: 'ప్రయాణీకుడు దొరకలేదు / నో-షో',
    luggageDispute: 'అదనపు లగేజీ / బరువు వివాదం',
    platformChangeNotice: 'అకస్మాత్తుగా ప్లాట్‌ఫారమ్ మార్పు',
    paymentDispute: 'చెల్లింపు / ఛార్జీల వివాదం',
    medicalEmergency: 'తక్షణ వైద్య / స్ట్రెచర్ మద్దతు',
    otherQuery: 'ఇతర స్టేషన్ సమస్య',
    pnrOptional: 'PNR / బుకింగ్ ID (ఐచ్ఛికం)',
    describeIssue: 'ప్లాట్‌ఫారమ్ వద్ద పరిస్థితిని వివరించండి...',
    submitTicket: 'స్టేషన్ డెస్క్‌కు టిక్కెట్ పంపండి',
    ticketSubmitted: 'టిక్కెట్ స్టేషన్ సూపర్‌వైజర్‌కు పంపబడింది',
    recentTickets: 'ఇటీవలి స్టేషన్ డెస్క్ టిక్కెట్లు',
    noRecentTickets: 'ఈరోజు ఎటువంటి టిక్కెట్లు సమర్పించబడలేదు.',
    protocolsTitle: 'ప్లాట్‌ఫారమ్ అసిస్టెంట్ భద్రతా నిబంధనలు & FAQs',

    // Modals & Popovers
    confirmOffDuty: 'ఆఫ్ డ్యూటీని నిర్ధారించండి',
    confirmOffDutyDesc: 'మీరు ఖచ్చితంగా ఆఫ్ డ్యూటీకి వెళ్లాలనుకుంటున్నారా? మీరు ఇకపై కొత్త ప్రయాణీకుల అభ్యర్థనలను స్వీకరించలేరు.',
    stayOnDuty: 'డ్యూటీలోనే ఉండండి',
    confirmGoOffDuty: 'అవును, డ్యూటీ ముగించు',
    activeJobWarning: 'యాక్టివ్ జాబ్ పురోగతిలో ఉంది',
    activeJobWarningDesc: 'మీకు యాక్టివ్ అసైన్ చేసిన జాబ్ ఉన్నప్పుడు మీరు ఆఫ్ డ్యూటీకి వెళ్లలేరు. దయచేసి ముందుగా మీ ప్రస్తుత పనిని పూర్తి చేయండి.',
    notificationsTitle: 'నోటిఫికేషన్‌లు',
    notificationsSub: 'స్టేషన్ డిస్పాచ్ & కార్యాచరణ హెచ్చరికలు',
    markAllRead: 'అన్నీ చదివినట్లు గుర్తించు',
    allCaughtUp: 'అన్నీ పూర్తయ్యాయి!',
    noPendingAlerts: 'పెండింగ్ హెచ్చరికలు లేవు. ప్రయాణీకుడు సహాయం కోరినప్పుడు మీకు వెంటనే తెలియజేయబడుతుంది.',
    newDispatch: 'కొత్త డిస్పాచ్',
    activeJobAlert: 'యాక్టివ్ జాబ్',
    stationRadar: 'స్టేషన్ రాడార్',
  },

  hi: {
    // Passenger Portal
    book: 'बुक',
    myTrips: 'मेरी यात्राएँ',
    selectServices: 'सेवाएँ चुनें',
    journeyDetails: 'यात्रा विवरण',
    confirmBooking: 'बुकिंग पक्की करें',
    heroA: 'यात्रा करें',
    heroB: 'भरोसे के साथ.',
    heroSub: 'सेवाएँ चुनें, सेकंडों में बुक करें, असिस्टेंट को लाइव ट्रैक करें.',
    verified: 'सत्यापित असिस्टेंट',
    station: 'स्टेशन',
    date: 'तारीख',
    time: 'समय',
    active: 'सक्रिय',
    history: 'इतिहास',
    viewLive: 'लाइव देखें',
    cancel: 'रद्द करें',
    noActive: 'कोई सक्रिय बुकिंग नहीं.',
    bookFirst: 'अपनी पहली यात्रा बुक करें',
    noHistory: 'अभी तक कोई यात्रा नहीं.',
    settings: 'सेटिंग्स',
    language: 'भाषा',
    appearance: 'थीम',
    light: 'लाइट',
    dark: 'डार्क',
    logout: 'लॉग आउट',
    safety: 'सुरक्षा',
    help: 'सहायता और समर्थन',
    myJobs: 'सौंपे गए काम',
    earnings: 'कमाई और समीक्षाएं',
    account: 'खाता',
    role: 'भूमिका',

    // Assistant Portal — Header & Duty
    assistantDuty: 'असिस्टेंट ड्यूटी',
    makingJourneyEasier: 'हर यात्रा को आसान बनाते हुए।',
    onDuty: 'ड्यूटी पर',
    offDuty: 'ड्यूटी से बाहर',
    stationDutyStatus: 'स्टेशन ड्यूटी स्थिति',
    goOnDuty: 'ड्यूटी शुरू करें',
    goOffDuty: 'ड्यूटी बंद करें',
    activatingDuty: 'ड्यूटी सक्रिय हो रही है...',
    deactivatingDuty: 'ड्यूटी बंद हो रही है...',
    liveDispatchDutyDesc: 'आप वर्तमान में रीयल-टाइम सहायता डिस्पैच प्राप्त कर रहे हैं:',
    offDutyDesc: 'यात्री सामान और सहायता अनुरोध प्राप्त करना शुरू करने के लिए ड्यूटी चालू करें।',
    dutyActiveMsg: 'अब आप ड्यूटी पर हैं:',
    waitingForRequests: 'यात्री अनुरोधों की प्रतीक्षा की जा रही है।',
    dutyInactiveMsg: 'अब आप ड्यूटी से बाहर हैं।',
    switchStation: 'स्टेशन चुनें',

    // Assistant Portal — Navigation Tabs
    dashboard: 'डैशबोर्ड',
    availableRequests: 'उपलब्ध अनुरोध',
    myAssignedJob: 'सौंपा गया काम',
    tripHistory: 'यात्रा इतिहास',
    earningsReviews: 'कमाई और समीक्षाएं',
    profile: 'प्रोफ़ाइल',
    support: 'सहायता और समर्थन',

    // Greetings & Section Headers
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    readyNextPassenger: 'आप अपने अगले यात्री के लिए तैयार हैं।',
    stationPresentTime: 'स्टेशन का वर्तमान समय',
    yourCurrentStation: 'आपका वर्तमान स्टेशन',
    currentDutyStatus: 'वर्तमान ड्यूटी स्थिति',
    stationDispatchActive: 'स्टेशन डिस्पैच सक्रिय',
    offDutyStandby: 'ड्यूटी बंद / स्टैंडबाय',
    switchDuty: 'ड्यूटी बदलें',
    dispatchBoard: 'डिस्पैच बोर्ड',
    activeAssignment: 'सक्रिय कार्य',
    completedTripsRecord: 'पूर्ण यात्रा रिकॉर्ड',
    payoutsFeedback: 'भुगतान और प्रतिक्रिया',
    dutyIdentity: 'ड्यूटी पहचान और बैज',
    helpDesk: 'सहायता केंद्र और सुरक्षा',

    // Metrics Cards
    stationRequests: 'स्टेशन अनुरोध',
    waitingForPickup: 'पिकअप की प्रतीक्षा',
    activeJobsCount: 'सक्रिय काम',
    inProgress: 'प्रगति पर है',
    completedJobsCount: 'पूरे किए गए काम',
    assistedPassengers: 'सहायता प्राप्त यात्री',
    totalEarnings: 'कुल कमाई',
    directPayouts: 'सीधा भुगतान',
    averageRating: 'औसत रेटिंग',
    verifiedReviews: 'सत्यापित समीक्षाएं',

    // Available Requests Section
    realTimeRequestsAt: 'पर रीयल-टाइम यात्री सहायता अनुरोध:',
    noRequestsAtStation: 'इस स्टेशन पर कोई लंबित यात्री अनुरोध नहीं है।',
    requestsAppearHere: 'सब कुछ अप-टू-डेट है। जब कोई यात्री सहायता का अनुरोध करेगा, तो वह यहाँ रीयल-टाइम में दिखाई देगा।',
    acceptRequest: 'अनुरोध स्वीकार करें',
    accepting: 'स्वीकार कर रहे हैं...',
    pnr: 'PNR',
    platform: 'प्लेटफॉर्म',
    coach: 'कोच / डिब्बा',
    luggageBags: 'सामान / बैग',
    fare: 'किराया',
    train: 'ट्रेन',
    passenger: 'यात्री',

    // Job Card & Actions
    manageJobSub: 'अपने वर्तमान यात्री सहायता कार्य को प्रबंधित और पूरा करें।',
    noActiveJob: 'अभी कोई सक्रिय काम नहीं है।',
    acceptToStart: 'अपना काम शुरू करने के लिए उपलब्ध अनुरोध बोर्ड से एक अनुरोध स्वीकार करें।',
    viewRequestsBtn: 'उपलब्ध अनुरोध देखें',
    atPlatform: 'मैं प्लेटफॉर्म पर हूँ',
    verifyStartService: 'सत्यापित करें और सेवा शुरू करें',
    completeService: 'सेवा पूरी करें',
    enterOtpPrompt: 'यात्री का 6-अंकों का OTP दर्ज करें',
    verifyOtp: 'OTP सत्यापित करें',
    verifying: 'सत्यापित हो रहा है...',
    otpVerified: 'OTP सत्यापित हुआ',
    callPassenger: 'कॉल करें',
    chatPassenger: 'चैट करें',
    platformConfirmed: 'पुष्ट',
    platformChanged: 'प्लेटफॉर्म बदला गया',
    emergencySos: 'स्टेशन आपातकालीन SOS',
    wheelchair: 'व्हीलचेयर सहायता',
    porterService: 'कुली / पोर्टर सेवा',
    otpInstruction: 'कोच तक पहुँचने पर यात्री से उनका 6-अंकों का गुप्त OTP पूछें।',

    // Trip History Section
    tripHistorySub: 'पूर्ण और पिछले सहायता कार्यों का विवरण',
    bookingId: 'बुकिंग आईडी',
    status: 'स्थिति',
    completed: 'पूरा हुआ',
    cancelled: 'रद्द किया गया',
    rating: 'रेटिंग',
    noCompletedJobs: 'अभी तक कोई काम पूरा नहीं हुआ।',
    completedWillAppear: 'आपके पूरे किए गए काम और यात्री रेटिंग यहाँ दिखाई देंगे।',
    servicesSelected: 'चयनित सेवाएं',

    // Earnings & Reviews Section
    earningsSub: 'अपनी आय, पूरी की गई यात्राओं और यात्री रेटिंग को ट्रैक करें',
    totalPayouts: 'कुल भुगतान',
    ratedTrips: 'रेटेड यात्राएं',
    passengerReviews: 'यात्री समीक्षाएं',
    noReviewsYet: 'अभी तक कोई यात्री समीक्षा नहीं है।',
    recentFeedback: 'हाल की यात्री प्रतिक्रिया',

    // Profile & Support Section
    profileSub: 'अपनी साख, ड्यूटी स्टेशन और परिचालन सुरक्षा का प्रबंधन करें',
    assistantProfile: 'असिस्टेंट प्रोफ़ाइल',
    kycStatus: 'केवाईसी स्थिति',
    verifiedBadge: 'सत्यापित',
    badgeNumber: 'बैज नंबर',
    phoneNumber: 'फ़ोन नंबर',
    assignedStation: 'सौंपा गया स्टेशन',
    helpEmergencySupport: 'सहायता और आपातकालीन सहायता',
    railwayHelpline139: 'डायल 139 - रेलवे यात्री हेल्पलाइन',
    policeHelpline112: 'डायल 112 - राष्ट्रीय आपातकालीन सहायता',
    safetyProtocols: 'परिचालन सुरक्षा दिशानिर्देश',
    supportSub: '24/7 प्लेटफॉर्म सहायता और आपातकालीन संपर्क',
    callNow: 'अभी कॉल करें',
    copyNumber: 'नंबर कॉपी करें',
    copied: 'कॉपी हो गया!',
    stationControlRoom: '139 नियंत्रण कक्ष',
    policeHelpline: '112 आपातकालीन हेल्पलाइन',
    stationHubInfo: 'स्टेशन डेस्क और आपातकालीन केंद्र',
    reportIssueTitle: 'स्टेशन डेस्क को परिचालन समस्या रिपोर्ट करें',
    reportIssueSub: 'कोच पर यात्री नहीं मिला, सामान का विवाद या प्लेटफॉर्म परिवर्तन? स्टेशन मास्टर को तत्काल टिकट भेजें।',
    category: 'समस्या की श्रेणी',
    passengerNoShow: 'यात्री नहीं मिला / कोच नो-शो',
    luggageDispute: 'अतिरिक्त सामान / वजन विवाद',
    platformChangeNotice: 'अचानक प्लेटफॉर्म परिवर्तन',
    paymentDispute: 'भुगतान / किराया विसंगति',
    medicalEmergency: 'तत्काल चिकित्सा / स्ट्रेचर सहायता',
    otherQuery: 'अन्य स्टेशन समस्या',
    pnrOptional: 'पीएनआर / बुकिंग आईडी (वैकल्पिक)',
    describeIssue: 'प्लेटफॉर्म की स्थिति का विवरण दें...',
    submitTicket: 'स्टेशन डेस्क को टिकट भेजें',
    ticketSubmitted: 'टिकट स्टेशन सुपरवाइजर को भेजा गया',
    recentTickets: 'हाल के स्टेशन डेस्क टिकट',
    noRecentTickets: 'आज कोई परिचालन टिकट नहीं उठाया गया।',
    protocolsTitle: 'प्लेटफॉर्म असिस्टेंट सुरक्षा नियम और अक्सर पूछे जाने वाले प्रश्न',

    // Modals & Popovers
    confirmOffDuty: 'ड्यूटी बंद की पुष्टि करें',
    confirmOffDutyDesc: 'क्या आप वाकई ड्यूटी बंद करना चाहते हैं? आपको नए यात्री अनुरोध प्राप्त नहीं होंगे।',
    stayOnDuty: 'ड्यूटी पर रहें',
    confirmGoOffDuty: 'हाँ, ड्यूटी बंद करें',
    activeJobWarning: 'सक्रिय काम प्रगति पर है',
    activeJobWarningDesc: 'सक्रिय काम होने पर आप ड्यूटी बंद नहीं कर सकते। कृपया पहले अपना वर्तमान काम पूरा करें।',
    notificationsTitle: 'सूचनाएं',
    notificationsSub: 'स्टेशन डिस्पैच और परिचालन अलर्ट',
    markAllRead: 'सभी पढ़े गए चिह्नित करें',
    allCaughtUp: 'सब कुछ अप-टू-डेट है!',
    noPendingAlerts: 'कोई लंबित अलर्ट नहीं है। जब कोई यात्री सहायता का अनुरोध करेगा तो आपको तुरंत सूचित किया जाएगा।',
    newDispatch: 'नया डिस्पैच',
    activeJobAlert: 'सक्रिय काम',
    stationRadar: 'स्टेशन रडार',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('rm-lang') || 'en');
  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;
  const setLanguage = (l) => {
    setLang(l);
    localStorage.setItem('rm-lang', l);
  };
  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
